export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_LOADED = "PRODUCTS_LOADED";

export const AUTH = {
	LOGIN_USER: "LOGIN_USER",
	USER_LOGGEDIN: "USER_LOGGEDIN",
	LOGOUT_USER: "LOGOUT_USER",
	USER_LOGGEDOUT: "USER_LOGGEDOUT",
	SET_ALERT: "SET_ALERT",
	RESET_ALERT: "RESET_ALERT",
};

export const NOTIFICATION = {
	SET_ALERT: "SET_ALERT",
	RESET_ALERT: "RESET_ALERT",
};

export const BUYER = {
	LOAD_BIDS: "LOAD_BIDS",
	BIDS_LOADED: "BIDS_LOADED",

	LOAD_BUYER_BIDS: "LOAD_BUYER_BIDS",
	BUYER_BIDS_LOADED: "BUYER_BIDS_LOADED",

	OVERRIDE_BID: "OVERRIDE_BID",
	BID_OVERRIDED: "BID_OVERRIDED",

	DELETE_BID: "DELETE_BID",
	BID_DELETED: "BID_DELETED",

	LOAD_BUYER_INSIGHTS: "LOAD_BUYER_INSIGHTS",
	BUYER_INSIGHTS_LOADED: "BUYER_INSIGHTS_LOADED",

	LOAD_BUYER_WISHLIST: "LOAD_BUYER_WISHLIST",
	BUYER_WISHLIST_LOADED: "BUYER_WISHLIST_LOADED",

	DELETE_WISHLIST: "DELETE_WISHLIST",
	WISHLIST_DELETED: "WISHLIST_DELETED",

	LOAD_BUYER_HISTORY: "LOAD_BUYER_HISTORY",
	BUYER_HISTORY_LOADED: "BUYER_HISTORY_LOADED",

	LOAD_BUYER_COMPLETED: "LOAD_BUYER_COMPLETED",
	BUYER_COMPLETED_LOADED: "BUYER_COMPLETED_LOADED",

	LOAD_BUYER_NOTIFICATIONS: "LOAD_BUYER_NOTIFICATIONS",
	BIDS_NOTIFICATIONS_LOADED: "BIDS_NOTIFICATIONS_LOADED",

	UPDATE_BUYER_NOTIFICATIONS: "UPDATE_BUYER_NOTIFICATIONS",
	BIDS_NOTIFICATIONS_UPDATED: "BIDS_NOTIFICATIONS_UPDATED",

	LOAD_BUYER_ADDRESS: "LOAD_BUYER_ADDRESS",
	BUYER_ADDRESS_LOADED: "BUYER_ADDRESS_LOADED",

	SAVE_BUYER_ADDRESS: "SAVE_BUYER_ADDRESS",
	BUYER_ADDRESS_SAVED: "BUYER_ADDRESS_SAVED",

	DELETE_BUYER_ADDRESS: "DELETE_BUYER_ADDRESS",
	BUYER_ADDRESS_DELETED: "BUYER_ADDRESS_DELETED",

	ADD_PAYMENT: "ADD_PAYMENT",
	PAYMENT_ADDED: "PAYMENT_ADDED",
};

export const SELLER = {
	LOAD_SELLER_PRODUCTS: "LOAD_SELLER_PRODUCTS",
	SELLER_PRODUCTS_LOADED: "SELLER_PRODUCTS_LOADED",

	LOAD_SELLER_INSIGHTS: "LOAD_SELLER_INSIGHTS",
	SELLER_INSIGHTS_LOADED: "SELLER_INSIGHTS_LOADED",

	ADD_PRODUCT: "ADD_PRODUCT",
	PRODUCT_ADDED: "PRODUCT_ADDED",

	UPDATE_PRODUCT: "UPDATE_PRODUCT",
	PRODUCT_UPDATED: "PRODUCT_UPDATED",

	LOAD_BIDS_WITH_USERS: "LOAD_BIDS_WITH_USERS",
	BIDS_WITH_USERS_LOADED: "BIDS_WITH_USERS_LOADED",

	UPDATE_BID: "UPDATE_BID",
	BID_UPDATED: "BID_UPDATED",

	LOAD_SELLER_HISTORY: "LOAD_SELLER_HISTORY",
	SELLER_HISTORY_LOADED: "SELLER_HISTORY_LOADED",

	LOAD_SELLER_COMPLETED: "LOAD_SELLER_COMPLETED",
	SELLER_COMPLETED_LOADED: "SELLER_COMPLETED_LOADED",

	CONFIRM_SHIPMENT: "CONFIRM_SHIPMENT",
	SHIPMENT_CONFIRMED: "SHIPMENT_CONFIRMED",
};
