export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_LOADED = "PRODUCTS_LOADED";

export const AUTH = {
	LOGIN_USER: "LOGIN_USER",
	USER_LOGGEDIN: "USER_LOGGEDIN",
	LOGOUT_USER: "LOGOUT_USER",
	USER_LOGGEDOUT: "USER_LOGGEDOUT",
	SET_ALERT: "SET_ALERT",
	RESET_ALERT: "RESET_ALERT",
};

export const NOTIFICATION = {
	SET_ALERT: "SET_ALERT",
	RESET_ALERT: "RESET_ALERT",
};

export const BID = {
	LOAD_BIDS: "LOAD_BIDS",
	BIDS_LOADED: "BIDS_LOADED",
	LOAD_BUYER_BIDS: "LOAD_BUYER_BIDS",
	BUYER_BIDS_LOADED: "BUYER_BIDS_LOADED",
	OVERRIDE_BID: "OVERRIDE_BID",
	BID_OVERRIDED: "BID_OVERRIDED",
	DELETE_BID: "DELETE_BID",
	BID_DELETED: "BID_DELETED",
};
